version: '3.9'

services:
  
  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    networks:
      - net

  django:
    container_name: django
    build: .
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cryptocurrency:/app/
    depends_on:
      - redis
    networks:
      - net
  
  # celery:
  #   container_name: celery
  #   build: .
  #   volumes:
  #     - ./cryptocurrency:/app/
  #   depends_on:
  #     - redis
  #     - django
  #   networks:
  #     - net

    
networks:
  net:
