version: '3.9'

services:
  
  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build: .
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - ./cryptocurrency:/app/
    depends_on:
      - redis
  
  celery:
    container_name: celery
    build: .
    command: celery --app=cryptocurrency worker -l INFO -B
    env_file:
      - ./.env
    volumes:
      - ./cryptocurrency:/app/
    depends_on:
      - redis


networks:
  net:
